/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_icu007_testjni01_JNILoader */

#ifndef _Included_work_icu007_testjni01_JNILoader
#define _Included_work_icu007_testjni01_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_icu007_testjni01_JNILoader
 * Method:    GetNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_icu007_testjni01_JNILoader_GetNativeString
  (JNIEnv *, jobject);

/*
 * Class:     work_icu007_testjni01_JNILoader
 * Method:    addNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_work_icu007_testjni01_JNILoader_addNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
